### ISSUE TITLE
Add Annotations for Service

### ISSUE THREAD

**Issue by ironf1st** [launchdarkly/ld-relay-helm#15]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to configure an AWS ELB when deploying this helm chart. However this is possible via [annotations](https://kubernetes.io/docs/concepts/services-networking/service/#ssl-support-on-aws). This would be very helpful to allow deployment of load balancers with their full configuration via this helm chart.

**Describe the solution you'd like**
Allow annotations to be made to the service like what is possible for ingress and pods.

**Comment by keelerm84** [comment]
Thank you for this feature request. I will let you know once we have this addressed.

Tracked internally as sc-176703

**Comment by keelerm84** [comment]
Support for this has been added in 1.1.0.
