### ISSUE TITLE
make HPA compatible with older kubernetes versions

### ISSUE THREAD

**Issue by guifl** [launchdarkly/ld-relay-helm#20]
**Is your feature request related to a problem? Please describe.**
We're using EKS and we're now running k8s in version 1.22, which doesn't support `autoscaling/v2` API for HPA

**Describe the solution you'd like**
Have a check to use a compatible version of HPA based on k8s version.

**Describe alternatives you've considered**
We tried overriding the chart locally, but it created us issues with our argocd integration

**Additional context**
Add any other context about the feature request here.

**Comment by keelerm84** [comment]
Acknowledging here that I have seen this issue and will respond to your PR.

**Comment by keelerm84** [comment]
Fixed in 1.2.0
