### ISSUE TITLE
Upgrade Relay proxy to version 7.0

### ISSUE THREAD

**Issue by GregdTd** [launchdarkly/ld-relay-helm#26]
Hello hello,

First of all: thank you for this helm chart ! 

**Is your feature request related to a problem? Please describe.**
Our proxy was not working because we used the last version of the [react-client-sdk](https://github.com/launchdarkly/react-client-sdk/releases/tag/3.0.4) which requires version 7.0 of the relay proxy as mentionned [here](https://docs.launchdarkly.com/sdk/client-side/react/web-migration-2-to-3).

**Describe the solution you'd like**
Either update the version of the relay proxy to match up-to-date documentation. 

**Describe alternatives you've considered**
Update [README.md](https://github.com/launchdarkly/ld-relay-helm/blob/main/README.md) to emphasis which version of SDK (Client side and Server side) can be used when using this helm chart.

**Additional context**
Add any other context about the feature request here.

**Comment by keelerm84** [comment]
Thank you for opening this issue. I will work on updating the chart to use a newer version of the relay soon. I will comment here once that is done.

**Comment by keelerm84** [comment]
v2.0.0 of the helm chart will now default to 7.2.1 of the relay proxy. I have also updated the README on the new 1.x branch to include a warning about context support.

Thank you again for raising this issue!
