### ISSUE TITLE
Add possibility to specify pod labels

### ISSUE THREAD

**Issue by kovaxur** [launchdarkly/ld-relay-helm#29]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We should be able to add additional labels to the pods. For us this is required for log collections.

**Describe alternatives you've considered**
No alternatives, as this is a de-facto way.

**Additional context**
N/A

**Comment by keelerm84** [comment]
As mentioned on the PR, I have some additional changes I'm going to work on adding before this is released. I will update you here once I have released the new version of this chart.

**Comment by keelerm84** [comment]
Released in 2.1.0
