### ISSUE TITLE
Add ability to add environment variable on deployment

### ISSUE THREAD

**Issue by uristernik** [launchdarkly/ld-relay-helm#33]
**Is your feature request related to a problem? Please describe.**
I want to use an environment variable with `valueFrom.fieldRef.fieldPath`. Because you are passing it to the config map, this is not an option at the moment.

**Describe the solution you'd like**
Have another value that renders to the containers environment variable

**Describe alternatives you've considered**
None right now

**Comment by keelerm84** [comment]
Will post here as well once the PR has been resolved.
