### ISSUE TITLE
No support for poddisruptionbudget

### ISSUE THREAD

**Issue by daniel-laszlo** [launchdarkly/ld-relay-helm#42]
**Describe the bug**
LD relay is a critical component in our stack and we cannot allow it to be down even when rolling nodes.

**Comment by keelerm84** [comment]
Thank you for filing this feature request. We will update this issue once we have taken action on your request.

Tracking internally as sc-207779.

**Comment by pjaak** [comment]
Hi @keelerm84 ,

I am happy to contribute to this and also https://github.com/launchdarkly/ld-relay-helm/issues/43

I can create a PR.

Thanks

**Comment by pjaak** [comment]
PR created: https://github.com/launchdarkly/ld-relay-helm/pull/46

**Comment by keelerm84** [comment]
Supported in 2.4.0
