### ISSUE TITLE
Upgrade Relay proxy to version 8.x

### ISSUE THREAD

**Issue by YorickH** [launchdarkly/ld-relay-helm#50]
**Is your feature request related to a problem? Please describe.**
With v8.0.0 being released 2 weeks ago we would like to update the proxy chart accordingly. Preventing us from upgrading our PHP SDK to v6.0

**Describe the solution you'd like**
Update the version of the relay proxy to match up-to-date documentation.

**Describe alternatives you've considered**
Manually bumping the image version on the helm chart on our side but would like to be able to use the stock helm chart.

**Additional context**
Add any other context about the feature request here.

**Comment by keelerm84** [comment]
I agree we need to update the default. As this is a breaking change, I'm going to take this opportunity to do some other small work on the project. I will let you know once it has been released.

> Manually bumping the image version on the helm chart on our side but would like to be able to use the stock helm chart.

Curious what you mean by stock helm chart. You are just bumping the version during the install command right?

**Comment by keelerm84** [comment]
Updated to 8.2.0 in v3.0.0

**Comment by YorickH** [comment]
@keelerm84 I was talking about the docker image version. It would entail updating `image.tag` to use the latest docker image. If the helm chart comes with a docker image tag I rather keep this as is and update the helm tag accordingly. 

Thanks for the update.

**Comment by keelerm84** [comment]
Yes, the helm chart comes with the ability to change this tag at any time. You don't have to wait for a release of this chart to affect that.

```shell
helm install ld-relay \
    --set image.tag=8.2.0 \
    --set relay.environment.LD_ENV_YourEnvironment=your-sdk-key \
    launchdarkly-ld-relay/ld-relay
```

You can also do this in a values file by setting

```yaml
image:
    tag: 8.2.0
```

Either way, it is good to have the default version be updated to v8 so this change was going to be made regardless.
